### ISSUE TITLE
watched paths in a mono-repo are rendered incorrectly for github actions

### ISSUE THREAD

**Issue by robwhitby** [springernature/halfpipe#104]
Bug report from @jshiell 

> I have a [halfpipe file](https://github.com/springernature/post-mortems/blob/main/website/.halfpipe.io.yml) in a subdirectory of a repo, but want it to trigger on all builds. My understanding was that it should do so if I didn’t specify any watched paths, but it [magically inserts filters](https://github.com/springernature/post-mortems/blob/main/.github/workflows/post-mortems.yml) for the subdirectory instead:
> 
> ```yaml
> "on":
>   push:
>     branches:
>     - main
>     paths:
>     - website**
>     - .github/workflows/post-mortems.yml
> ```

This is a bug in the actions renderer, it is automatically adding the sub-dir `website` to the watched paths. This doesn't happen in the Concourse renderer.

**Comment by jshiell** [comment]
Thanks @robwhitby !
