### ISSUE TITLE
create macOS ARM binary

### ISSUE THREAD

**Issue by robwhitby** [springernature/halfpipe#113]
add to the pipeline so it publishes to artifactory and github release

**Comment by jshiell** [comment]
As a second step, we need the `lipo` tool (part of XCode) to merge these into a universal binary, which requires a MacOS image.

There are some suggestions that [this port of CCTools](https://github.com/tpoechtrager/cctools-port) may let us use `lipo` on Linux.

**Comment by jshiell** [comment]
I've made us a Docker Image with `lipo` for Linux - https://github.com/springernature/docker-images/tree/master/build-cctools
