### ISSUE TITLE
keep github action versions up to date

### ISSUE THREAD

**Issue by robwhitby** [springernature/halfpipe#117]
let's improve how we keep all the actions up to date.

for example: 
https://github.com/springernature/halfpipe/blob/main/renderers/actions/actions.go#L127

maybe all we need to do is create a fully-feature workflow and use dependabot to alert us.

**Comment by efasel** [comment]
Thanks! Are you creating a new halfpipe release?

**Comment by efasel** [comment]
I guess the "update deps" release contains the corresponding changes: https://github.com/springernature/halfpipe/releases/tag/3.91.0 :slightly_frowning_face:
