### ISSUE TITLE
Add support for CF cli v8

### ISSUE THREAD

**Issue by robwhitby** [springernature/halfpipe#119]
Add support for CF cli v8 in the `deploy-cf` task

```
cli_version: optional([cf6|cf7], default="cf6")
```

https://github.com/cloudfoundry/cli/wiki/Versioning-and-Support-Policy

**Comment by stigtermichiel** [comment]
The halfpipe-cf-resource image has been updated with support for cf8.

https://github.com/springernature/halfpipe-deploy-resource/commit/3859ada1fe1652c4e376cea164796e17d89597e6

What is left is adding this to halfpipe and doing some tests.

**Comment by falk19** [comment]
release date to be defined
documentation to be finished
