### ISSUE TITLE
Halfpipe Linter warning about git repo difference

### ISSUE THREAD

**Issue by efasel** [springernature/halfpipe#135]
The Halfpipe Linter warns about potentially differing repo:

```
halfpipe > pipeline.yml
The Halfpipe Linter found problems in your project:

Triggers <https://ee.public.springernature.app/rel-eng/halfpipe/manifest#triggers>
  [WARNING] triggers[0] you have specified 'uri', make sure that its the same repo that you execute halfpipe in
```

I guess this is due to the repo now locally using "https" (since GitHub & Okta MFA), e.g. `https://github.com/springernature/cbs-price-service.git` and halfpipe creating a pipeline using SSH access, e.g. `uri: git@github.com:springernature/cbs-price-service.git`.

Can we teach the linter that new world?

**Comment by robwhitby** [comment]
hey Elmar, can you share the halfpipe manifest? Think this is just a warning when the uri in halfpipe doesn't match the git config.

I don't know why okta would make any difference here, should still be cloning over ssh

**Comment by efasel** [comment]
Sorry for the late reply.

That issue is not really an issue any more … :man_facepalming: … since I SSO authorized my SSH keys in GitHub. So there is no need to switch git access from SSH to HTTPS.
