### ISSUE TITLE
Halfpipe Linter: doesn't fail in case of too long host names as combination of application and space name

### ISSUE THREAD

**Issue by efasel** [springernature/halfpipe#136]
The Halfpipe Linter currently does not fail on a combination of application and space name which in the end leads to too long host names.

E.g. https://concourse.halfpipe.io/teams/gbs-integration/pipelines/gbs-integration-address-validation-service/jobs/stage%20app%20in%20staging%20env/builds/19#L622a0fef:81
```
$ cf map-route address-validation-service-CANDIDATE springernature.app -n address-validation-service-gbsintegrationlayer-staging-CANDIDATE
Creating route address-validation-service-gbsintegrationlayer-staging-CANDIDATE.springernature.app for org global-business-systems / space gbsintegrationlayer-staging as global-business-systems...
FAILED
Error resolving route:
Server error, status code: 400, error code: 210001, message: The route is invalid: host must be no more than 63 characters
exit status 1

```

* application name: https://github.com/springernature/gbs-integration-address-validation-service/blob/master/cf/manifest-stage.yml#L2
* pipeline: https://github.com/springernature/gbs-integration-address-validation-service/blob/master/.halfpipe.io

That would require that the linter parses not only the pipeline but also the (all) manifests. Therefore, this might be out of scope.

**Comment by stigtermichiel** [comment]
this has been implemented now. THanks for the suggestion!
