### ISSUE TITLE
Changing a pipeline's team does not remove the pipeline from the old team

### ISSUE THREAD

**Issue by npryce-springer** [springernature/halfpipe#14]
Changing the team of a pipeline does not remove the pipeline from the old team.  So we end up with two pipelines, one in each team.

**To Reproduce**

1. Create a halfpipe pipeline in one team
2. Change the pipeline definition to have a different team
3. Run `halfpipe upload`
4. The pipeline now exists in the new team but also still exists in the old team. 

**Expected behavior**

The pipeline should be removed from the old team.

**Workaround** 

Manually destroy the pipeline in the old team with the `fly` command

**Comment by simonjohansson** [comment]
How can we detect that the pipeline have changed team?

**Comment by npryce-springer** [comment]
Pipelines could have unique IDs?

**Comment by simonjohansson** [comment]
> Pipelines could have unique IDs?

How do you mean?

**Comment by robwhitby** [comment]
I am going to close this as it's out of scope of halfpipe. feel free to re-open if there's more to add though!
