### ISSUE TITLE
Can't save artifacts outside of project sub-directory in monorepo

### ISSUE THREAD

**Issue by robwhitby** [springernature/halfpipe#20]
`save_artifacts` and `save_artifacts_on_failure` don't let you save artifacts that are outside the task working dir. So projects in mono-repos can't reach outside into other sub-dirs of the git repo.

```
git
- my-project
- shared-lib
  - test-output
```
e.g. in this structure, the task working-dir is `my-project`, and it is not possible to save artifacts generated in `../shared-lib/test-output`.

The workaround is to copy all the required artifacts into one location as part of the task.

see https://github.com/springernature/halfpipe/blob/master/pipeline/pipeline.go#L842

**Comment by simonjohansson** [comment]
Implemented, but not released.
