### ISSUE TITLE
Upgrade actions hashicorp/vault-action from 2.7.4 to 2.8.0

### ISSUE THREAD

**Issue by hugocf** [springernature/halfpipe#233]
_Update: There’s a new version 2.8.0 ([2024-02-01 22:44 GMT](https://github.com/hashicorp/vault-action/releases/tag/v2.8.0))_

---

Our dependabot is fighting with Halfpipe’s auto-update 🙂 

Dependabot wants to bump `hashicorp/vault-action` from 2.7.4 to 2.7.5 in the actions workflow `.github/workflows/snd-directory.yml`: https://github.com/springernature/snd-directory/commit/49530cb3871685113ec357f642a45aeb391e3202

Only to immediately get reverted by Halfpipe’s `update-pipeline` feature: https://github.com/springernature/snd-directory/commit/f4c21e33463babf82b63ca7aaa32dc4c4f28a91e

Version 2.7.5 is very fresh ([2024-01-30 22:44 GMT](https://github.com/hashicorp/vault-action/releases/tag/v2.7.5)) but thought of letting you know since dependabot picks this very quickly.

**Comment by stigtermichiel** [comment]
Yeah this is a downside of using Halfpipe with the auto-update feature in Actions. The only thing we can do is to be as quick as possible with updating the Halfpipe cli.

**Comment by stigtermichiel** [comment]
This has been done now. Thanks for letting us know!
