### ISSUE TITLE
show more info about git commits in UI

### ISSUE THREAD

**Issue by robwhitby** [springernature/halfpipe#25]
The git resource only shows the git ref in the UI. It would be more useful to also show the commit message and a link to github.

The github-release resource (https://github.com/concourse/github-release-resource) demonstrates it is possible to show more fields:

in the resource versions view:
git: https://ci.concourse-ci.org/teams/main/pipelines/concourse/resources/ci
github-release: https://ci.concourse-ci.org/teams/main/pipelines/concourse/resources/gdn

in the build view:
https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/build-rc/builds/511

**Comment by robwhitby** [comment]
this open issue would also be useful without waiting for the new resources v2 epic

https://github.com/concourse/git-resource/issues/193

**Comment by simonjohansson** [comment]
https://github.com/concourse/git-resource/pull/269
