### ISSUE TITLE
Pin external actions to commit sha instead of version

### ISSUE THREAD

**Issue by robwhitby** [springernature/halfpipe#255]
we should pin third-party actions to a commit sha not version

e.g. `slackapi/slack-github-action@37ebaef184d7626c5f204ab8d3baff4262dd30f0`  not `slackapi/slack-github-action@v1.27.0`

see https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

**Comment by joergi** [comment]
if you want to easily updated yml files to not search yourself for the commit shas, you can use that Frizbee.
works pretty well for actions and docker images
https://github.com/stacklok/frizbee

**Comment by robwhitby** [comment]
hey @joergi, thanks for reminding me, should be all done now!
