### ISSUE TITLE
Docker compose tasks are slow

### ISSUE THREAD

**Issue by simonjohansson** [springernature/halfpipe#36]
Because they are not cached. Try the caching solution again now that we are on local SSDs

**Comment by robwhitby** [comment]
wiring up `halfpipe-docker-compose` to use the concourse image cache doesn't help much because it still has to `docker load` the images, and this takes about the same time as `docker pull` from gcr.

**Comment by robwhitby** [comment]
We are now trialling a feature `flatten-docker-compose` which converts docker-compose tasks into run tasks. A lot of docker-compose files only have one service, so could be run directly in Concourse instead - meaning the image would be cached.

```yaml
feature_toggles:
- flatten-docker-compose
```

It will only convert docker-compose tasks that have:
* one service
* `working_dir` set to same dir as `.halfpipe.io` file. (e.g. project sub dir in a mono-repo)
