### ISSUE TITLE
Ensure we have enough resources for each team

### ISSUE THREAD

**Issue by simonjohansson** [springernature/halfpipe#37]
Are we properly scaled for each team? Perception is that Concourse have become slower over time.

**Comment by robwhitby** [comment]
* when to add new workers
* when to split a team off into a dedicated set of workers
* how to optimise CPU/RAM specs of workers
* number of web nodes affects streaming of data to workers

**Comment by simonjohansson** [comment]
Practical task to analyse the current setup
