### ISSUE TITLE
Create a greasemonkey script that solves common issues.

### ISSUE THREAD

**Issue by simonjohansson** [springernature/halfpipe#42]
* Collapse the build logs..
* Show git data? 
* Delete pipeline button.
* __Show the gate.__
* Shows the version number.

**Comment by robwhitby** [comment]
We already have a starting point here:

https://github.com/springernature/halfpipe-docs/blob/master/static/userscripts/concourse.user.js

**Comment by simonjohansson** [comment]
If you start working on this break out in smaller issues/tasks plz.
