### ISSUE TITLE
One Concourse instance per domain?

### ISSUE THREAD

**Issue by simonjohansson** [springernature/halfpipe#44]

**Comment by robwhitby** [comment]
As part of this we could have users added to one GitHub team per domain. That way users would have full access to the entire concourse instance. They could then create teams in concourse to organise their pipelines. This lines up with the model in SNPaaS where there is one CF org per domain, and within that users can organise apps into spaces as they wish.

SN Domain (or department) === GitHub Team === CF Org === Concourse Instance

CF Spaces and Concourse Teams would be self-managed by users

Pros for users
* Users would have access to all pipelines in their domain
* Users can group pipelines as they wish in teams
* UI would have less pipelines so easier to navigate and faster
* Domains could manage their own scaling/costs

Cons for users
* multiple concourses might be confusing - where is my pipeline
* maybe having access to all pipelines in a domain is too much

**Comment by simonjohansson** [comment]
to start with, let's give each domain their own set of workers?

**Comment by robwhitby** [comment]
we are giving more teams their own set of workers. Can't do it by domain atm because it's not possible to assign multiple teams to a set of workers.

I renamed this issue back to being about completely separating domains into their own concourse deployments.
