### ISSUE TITLE
Scale down workers during the night

### ISSUE THREAD

**Issue by simonjohansson** [springernature/halfpipe#46]
Use our own set off workers and play around with in conjunction with lots of scheduled pipelines.

**Comment by robwhitby** [comment]
we now have a pipeline that scales down workers at night and back up in the morning:

https://concourse.halfpipe.io/teams/main/pipelines/halfpipe-bosh-concourse-scale-workers

```
halfpipe-infra/bosh/concourse-prod-vars.yml
halfpipe-infra/bosh/concourse-prod-vars-at-night.yml
```
