### ISSUE TITLE
Allow disabling of triggering via git (so we can use just cron instead)

### ISSUE THREAD

**Issue by sn-anura** [springernature/halfpipe#48]
(Submitted by @hilverd-springer)

**Is your feature request related to a problem? Please describe.**

We have a pipeline that runs security tests which takes many hours, and we only want to run it once a week. We're using a `timer` trigger but the problem is that the pipeline also gets triggered on all git changes.

**Describe the solution you'd like**

Maybe an option for not triggering on git changes could be added to Halfpipe?

**Describe alternatives you've considered**

We tried tweaking `watched_paths` and `ignored_paths` but that only resulted in the wrong git revision being picked up when the pipeline runs on the timer. For now we're working around this by manually setting `trigger: false` in the `get` step for the `git` resource in the generated Concourse config.

**Comment by robwhitby** [comment]
perhaps we could support this by adding `manually_trigger: optional(bool, default=false)` to each of the triggers (https://docs.halfpipe.io/manifest/#triggers) - or maybe just the git trigger to start with since it doesn't really make sense for the others at the moment.
