### ISSUE TITLE
README link requires auth

### ISSUE THREAD

**Issue by drahnr** [springernature/halfpipe#79]
The link for further info requires auth against some springer/../.. sso system. Is there a place where this info is available publicly?

**Comment by simonjohansson** [comment]
Hey @drahnr, sorry for the late reply!

Currently the Halfpipe docs are merged with our other super secret internal docs, but if your still curious I could see if I can desensitize it and share it?

**Comment by drahnr** [comment]
> Hey @drahnr, sorry for the late reply!
> 
> Currently the Halfpipe docs are merged with our other super secret internal docs, but if your still curious I could see if I can desensitize it and share it?

Yeah, that'd be great :) 

> Until then, you can check https://github.com/springernature/halfpipe/tree/master/e2e and see how the manifest relates to the rendered pipeline!

I'd prefer to read some docs, before deciding to dive into all examples :)
